default_platform(:ios)

platform :ios do
  before_all do
    spm(
      command: "generate-xcodeproj",
      xcconfig: "Sources/Config.xcconfig"
    )
  end
  
  lane :test do

    multi_scan(
      try_count: 1,
      parallel_testrun_count: 1,
      include_simulator_logs: true
    )

  end
end